name: dish_dash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  pdf: ^3.10.8
  printing: ^5.12.0
  provider: ^6.1.2
  url_launcher: ^6.2.6
    
  image_picker: ^0.8.5+3
  seo: ^0.0.7
  flutter_animate: ^4.5.0
  scroll_to_id: ^1.5.1
  card_swiper: ^3.0.1
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/OpenSans.ttf
    - assets/images/
