name: dish_dash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  awesome_snackbar_content: ^0.1.3
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  firebase_core: ^2.15.0
  firebase_storage: ^11.6.9
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  pdf: ^3.10.8
  printing: ^5.12.0
  provider: ^6.1.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/OpenSans.ttf
    - assets/images/
